#!/bin/bash

# Before running, make sure PASSPHRASE and GPG_KEY_ID are set.
# It's expected that a key matching the filename $GPG_KEY_ID.gpg is in the
# current directory.
#
# Example:
#
# PASSPHRASE=teddybear GPG_KEY_ID=ABCD0123 create_new_cold_storage

PREFIX=cs-btc-`date "+%Y%m%d"`-`date "+%N"`

{ for i in {1..20} ; do hexdump -v -e '/1 "%02X"' -n 32 /dev/urandom \
| format_key.py -p $PASSPHRASE "%a:%w:%W" ; done } | sort -u > keys.txt

< keys.txt gen_cold_wallet > keys.tex
pdflatex --shell-escape keys.tex
mv keys.pdf $PREFIX-print-then-shred.pdf

< keys.txt gen_cold_wallet -x > keys.tex
pdflatex --shell-escape keys.tex
mv keys.pdf $PREFIX-public-only.pdf

gpg --import ${GPG_KEY_ID}.gpg
gpg -a \
    -r ${GPG_KEY_ID} \
    --no-default-recipient --no-encrypt-to \
    -o $PREFIX.txt.asc \
    -e keys.txt

grep -oE "^[0-9a-zA-Z]+" keys.txt > $PREFIX-addresses.txt

shred -u keys*
