#!/usr/bin/python

# https://github.com/sowbug/cold-wallet-generator
#
# Generates a TeX file representing a nice-looking, scannable paper wallet
# suitable for cold storage.
#
# Accepts a series of addresses on stdin, where each line contains an
# Electrum-format <address:private_key> Bitcoin address.
#
# To generate a document with a lot of addresses, first put
# https://github.com/bkkcoins/misc/blob/master/keyfmt/keyfmt into your
# PATH, then try something like this:
#
# hexdump -v -e '/1 "%02X"' -n 32 /dev/urandom | keyfmt "%a:%w"
#
# For keyfmt to work, you'll also need to have installed
# https://github.com/warner/python-ecdsa to get the elliptic-curve stuff
# needed for key generation. (This project knows nothing specific about
# Bitcoin, but keyfmt does.)

import argparse
import datetime
import sys

def print_start():
  print r"""\documentclass[landscape, twocolumn]{book}
\setlength\columnsep{\dimexpr 1in/2\relax}
\setlength{\columnseprule}{0.4pt}
\usepackage{pst-barcode}
\usepackage{auto-pst-pdf}
\usepackage[margin=0.5in]{geometry}

\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot{}
\fancyfoot[RE,LO]{Generated %s}

\begin{document}

""" % (datetime.date.today())

def print_end():
  print r"""
\end{document}"""

def print_address(public, private, args):
  print r"""\item
\begin{pspicture}(1in,1in)
\psbarcode{%s}{eclevel=M width=0.8 height=0.8}{qrcode}
\end{pspicture}""" % (public)
  if not args.exclude_private_keys:
    print r"""\hfill
\begin{pspicture}(1in,1in)
\psbarcode{%s}{eclevel=H width=0.8 height=0.8}{qrcode}
\end{pspicture}""" % (private)
  print "\n"

  print public + "\n"
  if not args.exclude_private_keys and not args.exclude_private_key_text:
    print private

def print_lines(lines, args):
  print "\\begin{enumerate}\n\\setcounter{enumi}{0}"
  items_on_page = 0
  for line in lines:
    (pub, priv) = line.split(":")
    print_address(pub.strip(), priv.strip(), args)
    items_on_page += 1
    if items_on_page % 5 != 0:
      print "\\hrule"
    if items_on_page == 5:
      items_on_page = 0
      print "\\pagebreak\n"
  print "\\end{enumerate}\n"

def print_pages(args):
  if args.filename:
    f = open(args.filename)
    lines = f.readlines()
    f.close()
  else:
    lines = sys.stdin.readlines()
  print_start()
  print_lines(lines, args)
  print_end()

parser = argparse.ArgumentParser(description='Generates a TeX-format document ' +
  'that nicely formats a Bitcoin paper wallet for offline storage.')
parser.add_argument("filename", nargs='?',
  help="file of Electrum-format Bitcoin addresses to read. Otherwise reads from stdin.")
parser.add_argument("-x", "--exclude-private-keys", action="store_true",
  help="excludes private keys from document")
parser.add_argument("--exclude-private-key-text", action="store_true",
  help="excludes text representations of private keys from document")

args = parser.parse_args()
print_pages(args)
