#!/usr/bin/python

# Generates a TeX file representing a nice-looking, scannable paper wallet
# suitable for cold storage.
#
# Accepts a series of addresses on stdin, where each line contains an
# Electrum-format <address:private_key> Bitcoin address.
#
# To generate a document with a lot of addresses, first put
# https://github.com/bkkcoins/misc/blob/master/keyfmt/keyfmt into your
# PATH, then try something like this:
#
# hexdump -v -e '/1 "%02X"' -n 32 /dev/urandom | keyfmt "%a:%w"
#
# https://github.com/sowbug/cold-wallet-generator

import datetime
import sys

def print_start():
  print r"""\documentclass[landscape, twocolumn]{book}
\setlength\columnsep{\dimexpr 1in/2\relax}
\setlength{\columnseprule}{0.4pt}
\usepackage{pst-barcode}
\usepackage{auto-pst-pdf}
\usepackage[margin=0.75in]{geometry}

\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot{}
\fancyfoot[RE,LO]{Generated %s}

\begin{document}

""" % (datetime.date.today())

def print_end():
  print r"""
\end{document}"""

def print_address(public, private, include_private=True):
  print r"""\item
\begin{pspicture}(1in,1in)
\psbarcode{%s}{eclevel=M width=0.55 height=0.55}{qrcode}
\end{pspicture}
\footnotesize %s""" % (public, public)
  if include_private:
    print r"""\hfill \begin{pspicture}(1in,1in)
\psbarcode{%s}{eclevel=H width=0.55 height=0.55}{qrcode}
\end{pspicture}
""" % (private)

def print_lines(lines, include_private=True):
  print "\\begin{enumerate}\n\\setcounter{enumi}{0}"
  items_on_page = 0
  for line in lines:
    (pub, priv) = line.split(":")
    print_address(pub.strip(), priv.strip(), include_private)
    items_on_page += 1
    if items_on_page == 20:
      items_on_page = 0
      print "\\pagebreak\n"
  print "\\end{enumerate}\n"

lines = sys.stdin.readlines()
print_start()

print_lines(lines, True)
print "\\clearpage\n"
print_lines(lines, False)

print_end()
